

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

-- TRANSLATION 테이블 생성
CREATE TABLE translation (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    msg VARCHAR(255),
    lang VARCHAR(50),
    translation_text VARCHAR(255)
);


CREATE TABLE menu (
    id VARCHAR(20) PRIMARY KEY,
    app_code VARCHAR(10) NOT NULL,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(100),
    path VARCHAR(100),
    component_path VARCHAR(100),
    menu_level INT,
    parent_id VARCHAR(20),
    use_yn CHAR(1) DEFAULT 'Y',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

-- 부모-자식 관계를 위한 외래 키 제약 조건 추가
ALTER TABLE menu
ADD CONSTRAINT fk_menu_parent
FOREIGN KEY (parent_id) REFERENCES menu(id);
